[project]
name = "winiutils"
version = "4.14.50"
description = "A utility library for Python development"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = [
  "LICENSE",
]
authors = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
maintainers = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
keywords = [
  "pyrig",
]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
dependencies = [
  "cryptography>=49.0.0",
  "defusedxml>=0.7.1",
  "keyring>=25.7.0",
  "keyrings-alt>=5.0.2",
  "polars>=1.42.1",
  "pyrig-runtime>=3.5.2",
  "tqdm>=4.68.4",
]

[project.urls]
Changelog = "https://github.com/Winipedia/winiutils/releases"
Documentation = "https://Winipedia.github.io/winiutils"
Homepage = "https://github.com/Winipedia/winiutils"
Issues = "https://github.com/Winipedia/winiutils/issues"
Source = "https://github.com/Winipedia/winiutils"

[project.scripts]
winiutils = "pyrig_runtime.rig.cli.main:main"

[dependency-groups]
dev = [
  "bandit>=1.9.4",
  "deptry>=0.25.1",
  "detect-secrets>=1.5.0",
  "mkdocstrings[python]>=1.0.5",
  "pre-commit-hooks",
  "prek>=0.4.8",
  "pyrig>=18.3.4",
  "pyrig-pypi>=3.1.2",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-mock>=3.15.1",
  "pytest-randomly",
  "pytest-xdist>=3.8.0",
  "ruff>=0.15.21",
  "rumdl>=0.2.30",
  "ryl",
  "shellcheck-py",
  "shfmt-py",
  "tombi",
  "ty>=0.0.58",
  "types-defusedxml>=0.7.0.20260504",
  "types-tqdm>=4.68.0.20260608",
  "typos>=1.48.0",
  "zensical>=0.0.52",
]

[build-system]
requires = [
  "uv-build",
]
build-backend = "uv_build"

[tool.deptry]
root = "src"

[tool.deptry.per_rule_ignores]
DEP002 = [
  "pyrig-runtime",
]

[tool.pytest]
addopts = [
  "--cov-branch",
  "--cov-fail-under=90",
  "--cov-report=term-missing:skip-covered",
  "--cov=winiutils",
  "--dist=worksteal",
  "--numprocesses=auto",
  "--report-chars=a",
]
filterwarnings = [
  "error",
]
strict = true
testpaths = [
  "tests",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = [
  "CPY001",
]
select = [
  "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
