name: Bug Report
description: Report a bug
title: '[Bug]: '
labels:
- bug
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: A clear description of the bug
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: Steps to Reproduce
    value: "1. \n2. \n3. \n"
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual Behavior
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: OS, version, relevant dependencies
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: Relevant log output (auto-formatted as code)
    render: shell
  validations:
    required: false
