---
"name": "Bug Report"
"description": "Report a bug"
"labels":
  - "bug"
"title": "[Bug]: "
"body":
  -
    "type": "textarea"
    "attributes":
      "label": "Description"
      "description": "A clear description of the bug"
    "id": "description"
    "validations":
      "required": true
  -
    "type": "textarea"
    "attributes":
      "label": "Steps to Reproduce"
      "value": |-
        1.
        2.
        3.
    "id": "steps"
    "validations":
      "required": true
  -
    "type": "textarea"
    "attributes":
      "label": "Expected Behavior"
    "id": "expected"
    "validations":
      "required": true
  -
    "type": "textarea"
    "attributes":
      "label": "Actual Behavior"
    "id": "actual"
    "validations":
      "required": true
  -
    "type": "textarea"
    "attributes":
      "label": "Environment"
      "description": "OS, version, relevant dependencies"
    "id": "environment"
    "validations":
      "required": false
  -
    "type": "textarea"
    "attributes":
      "label": "Logs"
      "description": "Relevant log output (auto-formatted as code)"
      "render": "shell"
    "id": "logs"
    "validations":
      "required": false
...
