name: Build
'on':
  workflow_dispatch: {}
  workflow_run:
    workflows:
    - Health Check
    types:
    - completed
    branches:
    - main
permissions: {}
run-name: Build
defaults:
  run:
    shell: bash
env:
  PYTHONDONTWRITEBYTECODE: 1
  UV_NO_SYNC: 1
jobs:
  artifacts:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: true
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event
      != 'schedule' }}
    steps:
    - name: Checkout Repository
      id: checkout-repository
      uses: actions/checkout@main
    - name: Setup Version Control
      id: setup-version-control
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Package Manager
      id: setup-package-manager
      uses: astral-sh/setup-uv@main
      with:
        python-version: '3.14'
    - name: Install Dependencies
      id: install-dependencies
      run: uv sync
    - name: Build Artifacts
      id: build-artifacts
      run: uv run pyrig build
    - name: Upload Artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@main
      with:
        name: winiutils-${{ runner.os }}
        path: dist
