---
"name": "Release"
"on":
  "workflow_run":
    "branches":
      - "main"
    "types":
      - "completed"
    "workflows":
      - "Health Check"
"defaults":
  "run":
    "shell": "bash"
"env":
  "PYTHONDONTWRITEBYTECODE": 1
  "UV_NO_SYNC": 1
"run-name": "Release"
"jobs":
  "publish":
    "if": |-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    "permissions":
      "contents": "write"
    "runs-on": "ubuntu-latest"
    "steps":
      -
        "name": "Checkout Repository"
        "id": "checkout-repository"
        "uses": "actions/checkout@main"
        "with":
          "persist-credentials": false
      -
        "name": "Setup Package Manager"
        "id": "setup-package-manager"
        "uses": "astral-sh/setup-uv@main"
        "with":
          "python-version": "3.14"
      -
        "name": "Configure Repository"
        "id": "configure-repository"
        "run": "bash .github/configure.sh"
        "env":
          "GH_TOKEN": "${{ secrets.REPO_TOKEN }}"
      -
        "name": "Create Release"
        "id": "create-release"
        "run": |-
          gh \
          release \
          create \
          $(uv version --short) \
          --title=$(uv version --short) \
          --generate-notes
        "env":
          "GH_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
...
